### ISSUE TITLE
Custom attributes

### ISSUE THREAD

**Issue by sillen102** [lpotthast/axum-keycloak-auth#1]
How can I access custom attributes? I have set the ```persist_raw_claims(true)``` but now what?

I have tried reading the code and in the code if persist_raw_claims is set there should be a tuple looking like so: ```(RawClaims, KeycloakToken<String>)``` but doing this in a handler function isn't working: ```Extension<(RawClaims, KeycloakToken<String>)>```.

**Comment by sillen102** [comment]
Ok, I think I figured it out. You have to do two separate extractors, one for KeycloakToken and one for RawClaims.

**Comment by dev-sap** [comment]
Hi, I faced the same situation today. Here's how I solved it:
```

Router::new()
//...
.route_layer(axum::middleware::from_fn(database_middleware::set_pool))
//...


//in my database_middleware.rs
pub async fn set_pool(
    Extension(raw_claims): Extension<RawClaims>,
    req: Request,
    next: Next,
) -> Result<Response, StatusCode> {
    
    //extrat tenant from keycloak
    let tenant = if let Some(Value::String(tenant)) = raw_claims.get("tenant") {
        tenant
    } else {
        println!("Tenant key not found in the raw_claims");
        return Err(StatusCode::UNAUTHORIZED);
    };

    println!("Tenant: {}", tenant);

    // ...
    
}

```
