### ISSUE TITLE
Let user specify retry strategy for fetching public keys

### ISSUE THREAD

**Issue by dspicher** [lpotthast/axum-keycloak-auth#10]
The retry strategy is currently [hardcoded](https://github.com/lpotthast/axum-keycloak-auth/blob/6ee57a9ccb303d70eedd8ab1a711f4500381c6b4/src/instance.rs#L168-L173). It would be great if the user could set this according to their needs.

I would be happy to submit a PR if you'd like.

**Comment by lpotthast** [comment]
Yeah, this would be a great addition!
