### ISSUE TITLE
Inability to choose TLS implementation

### ISSUE THREAD

**Issue by dspicher** [lpotthast/axum-keycloak-auth#11]
It is common for packages that require TLS to give the user the option to choose an implementation via feature flags. See for example `reqwest`'s [feature flags](https://docs.rs/crate/reqwest/latest/features). Could you also support this?

I'd be happy to submit a PR if you'd like.

**Comment by lpotthast** [comment]
Feel free to open a PR for it :)

**Comment by Mek101** [comment]
Has this been implemented? Using `axum-keycloak-auth  = { version = "0.5", features = [ "rustls-tls" ] }` ends in a compilation error
```
0.492 error: failed to select a version for `axum-keycloak-auth`.
0.492     ... required by package `my-crate (/app)`
0.492 versions that meet the requirements `^0.5` (locked to 0.5.0) are: 0.5.0
0.492 
0.492 the package `my-crate` depends on `axum-keycloak-auth`, with features: `rustls-tls` but `axum-keycloak-auth` does not have these features.
0.492 
0.492 
0.492 failed to select a version for `axum-keycloak-auth` which could resolve this conflict
```
